== Un corto relato de Bárbara Blaugdone

En mis tiernos años de juventud, yo temía al Señor y temía ofenderle,
y era celosa y diligente en la profesión religiosa en la que fui criada.
Buscaba al Señor con fervor, aunque no sabía dónde hallarlo,
hasta que fui dirigida por dos Amigos--John Audland y John Camm^
footnote:[ Véase "`Un Testimonio acerca de la gloriosa
mañana del día de la visitación del amor de Dios,
y del grande y poderoso poder del Señor,
que apareció en y con Sus dos preciosos siervos John Camm y John Audland,
quienes llegaron a esa ciudad en el año 1654`",
en el capítulo cuarto del Journal of Charles Marshall,
www.friendslibrary.com.]--quienes vinieron del norte de Inglaterra en el año 1654.
El comportamiento y porte de ellos eran tales,
que me predicaron aun antes de haber abierto la boca,
y entonces me fue revelado que ellos tenían el evangelio
eterno para predicar en esta ciudad.
Cuando abrieron la boca,
fui llevada a bendecir a Dios por haber vivido para
oír la predicación del evangelio eterno;
pues dirigieron nuestras mentes a la luz de Cristo y nos exhortaron a esperar en ella,
en lo cual fui diligente, y con el tiempo llegué a experimentar su virtud.
A medida que cualquier mal me era mostrado, yo me apartaba de él,
y de buena gana tomaba la cruz y rendía obediencia incluso en las cosas pequeñas,
como la sencillez en el hablar y en el vestir.
Cuando iba a los lugares públicos y a las casas del campanario para hablar la verdad,
las personas se ofendían tanto que comenzaron a sacar a sus niños de mi escuela,
de modo que perdí casi todo mi sustento,
y con frecuencia me mantenían en prisión hasta por un cuarto de año a la vez.
Grandes fueron mis sufrimientos en aquellos días,
pero el Señor me llenó tan plenamente de Su poder que fui preservada en todo;
porque los diligentes y fieles prosperaban entonces, como prosperan hoy.

Por lo tanto, mi consejo para los Amigos es que permanezcan en el poder de Dios;
porque no hay otro camino para ser preservados,
ni para recibir vida y salvación--este es mi testimonio a favor de Dios.
Porque cualquiera que rehúye la cruz se aparta del poder,
y perderá su camino y deshonrará a Dios.
Pero quien se mantiene en la fe y permanece en el poder, permanece seguro.
Yo he tenido viva experiencia de esto,
y he sentido por largo tiempo publicarlo para el
beneficio de aquellos que están pasando ahora,
o aún han de pasar, por sufrimientos.
Por esta razón declaro mi experiencia.

Así, pues, queridos Amigos, la cruz es el camino hacia la corona de vida y de gloria;
y aquellos que perseveren fieles y obedientes obtendrán la corona eterna,
mientras que los desobedientes la perderán. Relato mi experiencia
de los tratos del Señor conmigo en mi viaje espiritual,
para beneficio de los que, con corazón recto, viajan después de mí. Y puedo decir,
para gloria de Dios,
que Él nunca me movió a hacer cosa alguna sin también haberme dado el poder para realizarla,
y además hacerla eficaz,
aunque muchas veces pasé por pruebas y sufrimientos al llevarla a cabo.
En efecto, el poder de Dios obraba en mí mucho tiempo antes de que yo supiera lo que era,
pero cuando los Amigos llegaron y predicaron el evangelio eterno,
mi entendimiento fue abierto.
Por tanto, tomé la cruz y entré en verdadera obediencia,
y hallé que el Señor me limpiaba mediante Su poder,
y me hacía una vasija apta para Su servicio.

Después de haber trabajado en la obra del evangelio por un tiempo en casa,
Él me llamó a salir para hacerlo en otros lugares.
Sentía tal pavor, reverencia y temor del Señor,
que Su Espíritu tuvo que luchar mucho conmigo antes de que pudiera abrir mi boca.
Pero la palabra del Señor vino a mí en una reunión, diciendo:
"`Jehová tendrá guerra contra Amalec de generación en generación;`"^
footnote:[ Éxodo 17:16]
y el poder y Espíritu del Señor era tan fuerte en mí,
que me puso de pie y me constriñó a decir estas palabras ante el pueblo;
porque nunca fui apresurada ni inclinada a hablar en el nombre del Señor.

Entonces el Señor hizo que me abstuviera de toda carne, vino y cerveza,
y por espacio de un año entero tomé únicamente agua.
Pero durante ese tiempo el Señor hizo que creciera y prosperara en la Verdad.
Luego me envió a llamar a las personas a que se apartaran de sus ídolos mudos,
y sufrí muchos encarcelamientos por causa de ello.
Sin embargo, era continuamente impulsada a ir,
y el Señor me dio dominio sobre toda oposición, de modo que podía ir a todos,
y decir lo que tenía que decir, y luego regresar en silencio.
Una vez,
mientras Mary Prince y yo salíamos del brazo de una reunión en la casa de George Bishop,
un hombre grosero se acercó y nos maltrató. Le arrancó el sombrero a Mary Prince,
y hundió un cuchillo o instrumento agudo a través
de toda mi ropa y me lo clavó en el costado,
el cual, de haber entrado un poco más, me habría matado;
pero mi alma estaba tan llena de la Verdad,
que gustosamente habría podido entregar mi vida por Ella ese día.

Luego fui movida a ir a Marlborough, al mercado y a la casa del campanario allí,
donde tuve mucho servicio.
Por esto fui puesta en prisión durante seis semanas,
en las cuales ayuné seis días y seis noches, sin comer pan ni tomar agua,
ni nada terrenal; pero llegué a conocer lo que es alimentarse de la Palabra,
y experimenté que el hombre no vive sólo de pan,
sino de toda palabra que sale de la boca del Señor.
Cuando fui liberada fui a ver a Isaac Burges,
el hombre que me había enviado a prisión, y conversé con él,
y fue convencido de la Verdad, pero no quiso tomar la cruz.
No obstante, después mostró mucho amor hacia los Amigos,
los apoyó en toda ocasión y nunca más persiguió a ninguno.
Y cuando vino a la ciudad de Bristol,
vino a verme a mi casa y confesó que no podía tomar la cruz,
aunque sabía que era el verdadero camino.

Un tiempo después fui movida a ir a Devonshire, a Melton, Barnstaple y Bideford,
donde una prisión fue mi porción en todos esos lugares.
Luego fui a la casa del conde de Bath, para llamarlos a salir de la vanidad,
porque en mis años de juventud había pasado mucho tiempo allí en vanidades.
Pedí hablar con la condesa, pero no me dejaron entrar; sin embargo,
uno de los siervos que me conocía me indicó que fuera a la puerta trasera,
diciéndome que la señora de la casa saldría por allí
e iría conmigo al jardín. Pero en lugar de eso,
soltaron a su perro lobo que corrió con furia hacia mí para devorarme;
pero justo cuando se lanzaba sobre mí, el poder de Dios hirió al perro,
de modo que repentinamente gimió y huyó llorando y cojeando,
y vi con claridad que la mano del Señor había intervenido para preservarme.
¡Bendito sea Su nombre!
Entonces salió la señora de la casa,
permaneció quieta y escuchó todo lo que yo tenía que decirle; y cuando terminé,
me dio las gracias, pero nunca me invitó a entrar en su casa,
aunque yo había comido y bebido en su mesa y me había alojado muchas veces allí.

Entonces fui movida a ir a Great Torrington en Devonshire, a la casa del campanario.
En ese lugar había un sacerdote verdaderamente perverso,
aunque no me fue dado decirle mucho a él, sino al pueblo.
Y cuando terminé de hablar esa mañana, me retiré a mi alojamiento,
y puse por escrito algunas cosas que no había tenido
tiempo de declarar en la casa del campanario.
Pero los alguaciles llegaron a mi habitación y me quitaron mi escrito,
y me ordenaron acompañarlos a su adoración, intentando tenderme una trampa.
Yo les respondí que ellos no me permitirían hablar allí,
y que no conocía ley alguna que me obligara ir dos veces en un día,
y que todos ellos sabían que yo había estado allí en la mañana, así que no iría.

Al día siguiente el alcalde me mandó a llamar, y cuando fui a él,
el sacerdote estaba presente.
El alcalde se comportó con moderación y era renuente a enviarme a prisión,
pero el sacerdote estaba muy empeñado y dijo que yo debía ser azotada por ser una vagabunda.
Le pedí que probara que alguna vez le había pedido a una persona un bocado de pan,
pero él dijo que yo había quebrantado la ley al hablar en su iglesia.
Fue tan insistente con el alcalde,
que él finalmente emitió una orden de la corte y me envió a la prisión de Exeter,
a veinte millas de distancia, donde permanecí durante algún tiempo.
Allí el Señor me ordenó ayunar catorce días y catorce noches, sin probar pan o agua,
o cosa terrenal alguna,
lo cual llevé a cabo como testimonio contra ese pueblo
que profesaba la verdad pero andaba en tinieblas,
y allí permanecí hasta las siguientes sesiones de la corte,
sin jamás haber sido llevada a juicio.

Después de que las sesiones de la corte finalizaron,
un alguacil menor me mandó a llamar y leyó una ley
que no tenía relación alguna con mi caso,
y luego hizo que pasara una noche entre un gran grupo de gitanos
que estaba en ese momento en la prisión. Al día siguiente,
el alguacil mayor llegó con un oficial de la parroquia y me llevaron a
una habitación donde él me azotó hasta que la sangre corrió por mi espalda,
aunque nunca me estremecí ante ningún golpe.
El Señor hizo que me regocijara por haber sido tenida por digna de padecer por Su nombre,
y mientras él me azotaba, yo cantaba en voz alta.
El oficial dijo: "`¿Cantas?
¡Pronto te haré llorar!`"
Y con eso, descargó más azotes y con mucha fuerza.
En verdad,
jamás olvidaré la gran experiencia del amor y del poder de Dios que tuve aquel día,
y por eso puedo hablar para alabanza y gloria de Su nombre;
porque si el oficial de la parroquia me hubiera azotado
hasta la muerte en el estado en que entonces me hallaba,
no habría sentido temor ni turbación alguna.
Ann Speed fue testigo ocular de la crueldad de estos hombres,
pues se quedó mirando por la ventana, y lloró amargamente.
Cuando el alguacil mayor vio que la maldad del hombre no podía conmoverme,
le ordenó desistir,
porque ya había sobrepasado sus órdenes en el número de azotes que me había dado.

Cuando él se marchó, Ann Speed entró y curó mis heridas;
y al día siguiente me echaron junto con todos los gitanos,
y el oficial nos obligó a caminar poco más de dos kilómetros fuera de la ciudad.
Pero tan pronto como nos dejó,
yo regresé y volví a la prisión para visitar a mis amigos
que estaban encarcelados allí en ese mismo tiempo.
Después de despedirme de ellos, fui a Topsham, donde hubo una hermosa reunión de Amigos,
entre quienes fui dulcemente reconfortada,
y me quedé allí una noche antes de regresar a mi casa, en Bristol.
En mis viajes, con frecuencia recorrí muchos kilómetros por extensas llanuras,
sin conocer el camino,
salvo en la medida en que el Señor--que estaba conmigo--me dirigía.
En todo esto he tenido gran experiencia del amor y del poder del
Señor hacia mí. ¡Bendito sea Su nombre para siempre!
Nunca olvidaré Su amorosa bondad para conmigo en mis angustias.

En mis viajes cerca de Bridgewater,
fui a hablar con un sacerdote que había conocido anteriormente, un tal Edward Piggot;
y cuando regresé a la posada, donde ya había pagado por mi alojamiento,
no quisieron dejarme entrar.
Así que busqué un refugio para protegerme de la intensa helada,
y encontré que el chiquero estaba barrido y muy limpio,
y que el comedero estaba volteado, sin ningún cerdo dentro.
Me senté entonces sobre el comedero, y ese fue mi alojamiento toda aquella noche.
Tampoco pude encontrar hospedaje la noche siguiente,
pero estuve dispuesta a pasarla en un granero.
El Señor me ejercitó en la paciencia por medio de todas estas cosas.

Luego fui a Bideford, donde me llevaron al ayuntamiento,
y me registraron para ver si yo llevaba un cuchillo o unas tijeras.
Al día siguiente me llevaron ante el alcalde por
hablar en una reunión privada entre Amigos,
y él conversó largamente conmigo, y le fue dado entendimiento con respecto a lo que dije,
y lo recibió. Finalmente, abrió dos puertas, una frente a la otra,
y dijo que me dejaba a mí la elección: si quería ir a prisión de nuevo o regresar a casa.
Le dije que prefería la libertad que las cadenas; así que me dirigí hacia mi casa.
Entonces, el alcalde cogió su caballo y me siguió,
porque había en él una medida de ternura,
y me pidió que cabalgara detrás de él. Pero noté que,
cuando alguien a quien él conocía se cruzaba con nosotros en el camino,
él se quedaba atrás y me dejaba a mí delante,
y tan pronto como la persona se había alejado, me volvía a alcanzar.
Así cabalgó conmigo por unos cinco o seis kilómetros, conversando todo el trayecto;
y cuando nos despedimos, fui movida a arrodillarme y orar por él;
en ese momento él estaba muy serio.
Después de esto, llegó a ser un hombre muy serio y sobrio,
y poco tiempo después murió. Pero al poco tiempo de haber regresado a mi casa,
le escribí una vez más antes de que muriera.

Entonces fui movida por el Señor a ir a Basingstoke,
y tratar de obtener la libertad de dos Amigos, a saber, Thomas Robison y Ambrose Rigge^
footnote:[Ver [.book-title]#Selección de la Vida de Ambrose Rigge,#
www.bibliotecadelosamigos.org],
que habían sido hechos prisioneros en la primera reunión de Amigos en ese lugar.
Pero cuando llegué no me dejaron verlos.
Tenía una carta de John Camm para ellos, y se las pasé por una rendija en la puerta,
y luego fui a ver al alcalde para pedir la liberación de ellos.
Me dijo que si podía ver la carta que yo les había pasado, serían liberados.
Le dije que podía, así que fui y la recogí para que la viera.
Después de que la leyó, y vio que no había mal en ella,
me dijo que sacaría a mis hermanos, pero que no lo haría de inmediato.
Con todo, al día siguiente, que era primer día de la semana, tuvimos una hermosa reunión,
y saliendo de ella,
me encontré con el sacerdote del lugar y le hablé lo que
el Señor había puesto en mi corazón. A los pocos días,
los Amigos fueron liberados; así prosperó el Señor mi viaje.

En el año 1656, fui movida a ir a Irlanda, y fui en una embarcación con rumbo a Cork.
Pero el Señor dispuso que hubiera muy mal tiempo,
y el barco fue desviado a Dublín. Los marineros, al ver la tormenta,
dijeron que yo era la causa porque era cuáquera,
y conspiraron para lanzarme por la borda.
Pero al enterarme de su plan,
fui al capitán del barco y le dije lo que sus hombres habían planeado,
y que si lo permitía, mi sangre sería demandada de las manos de él. Entonces,
él le ordenó a la tripulación que no se metieran conmigo.
Después de esto, cayó sobre nosotros una gran tormenta un primer día,
y fui movida por el Señor a subir a la cubierta y
hablarles a los marineros y orar por ellos.
Todos se quedaron muy quietos,
y dijeron que me debían más a mí que al sacerdote de ellos,
porque yo había orado por ellos,
y él no había podido abrir su boca ni decirles nada en ese momento.
Estuvimos seis días y seis noches en el mar, y el capitán mismo no sabía dónde estaba,
ni en qué dirección iba,
hasta que nos encontramos en el puerto de Dublín. Y aunque tuvimos mucho tiempo tormentoso,
no sufrimos ningún tipo de pérdida o daño,
por lo que el capitán dijo que nunca antes había estado en un clima tan adverso
sin sufrir daños. Arribamos a Dublín el mismo día en que Francis Howgill^
footnote:[Véase [.book-title]#Selección de la vida de Francis Howgill#
y [.book-title]#Algunos de los misterios del Reino de Dios declarados# por
Francis Howgill, en www.bibliotecadelosamigos.org]
y Edward Burrough^
footnote:[Véase [.book-title]#The Life of Edward Burrough,# en www.friendslibrary.com.]
fueron desterrados de Irlanda.

Entonces entendí cuál era mi servicio allí,
y fui movida por el Señor a ir al lord diputado de Irlanda.^
footnote:[Este era Henry Cromwell, hijo de Oliver Cromwell,
Lord Protector de la Mancomunidad de Inglaterra.]
Cuando fui a verlo, la gente me decía: "`No hay forma de que hables con él;
¿acaso no sabes que él desterró de la nación a dos de tus Amigos apenas ayer?`"
Pero fui en fe, y el poder del Señor estaba sobre mí con gran peso.
Me encontré con el secretario y le pedí que me ayudara a hablar con el diputado.
Él me respondió que no creía poder ayudarme.
Le dije:
"`Serías tan amable de subir y decirle al diputado
que hay una mujer abajo que desea hablar con él;
si él se niega, me daré por satisfecha.`"
Así que subió, y pronto bajó un hombre para llevarme a otra sala.

Después de haber estado allí un rato, salió un hombre de la cámara del diputado,
y muchos otros agolpados alrededor de pie ante él, habiéndose quitado los sombreros.
Ellos sabían que yo nunca antes había visto al diputado,
pero me fue dado un sentir de que ese hombre no era el diputado,
sino más bien un sacerdote.
Cuando la sala estuvo casi llena de gente, me preguntaron:
"`¿Por qué no le das tu mensaje a nuestro lord diputado?`"
Respondí: "`Cuando vea al diputado, entonces le daré mi mensaje.`"
Después de un rato salió el verdadero diputado y se sentó en un sillón.
Me puse de pie y le hablé todo lo que el Señor había puesto en mí,
y le advertí que tuviera cuidado de no ser hallado
peleando contra Dios al oponerse a la verdad,
y persiguiendo al inocente, sino que fuera como el sabio Gamaliel, y dejara el asunto,
porque si era de Dios permanecería,
pero si era del hombre caería. Le dije que yo era consciente
de que la enemistad no provenía tanto de él,
sino que era incitado a ella por magistrados perversos y sacerdotes corruptos;
pero que el pueblo de Dios era tan querido para Él hoy, como siempre lo había sido,
y que cualquiera que lo tocara, tocaba la niña de Su ojo.
"`Pero`", le dije,
"`en tu nombre y por tu autoridad se está haciendo
mucho daño al pueblo de Dios en toda la nación,
y esto te pesará mucho al final.`"
Luego le dije que los maestros del pueblo los hacían errar,
y que él sabía cuál sería la porción de esos sacerdotes.
Y cada vez que yo tocaba este tema, él le decía al sacerdote que estaba allí:
"`Esto es para ti, señor Harrison.`"
El poder y la presencia del Señor eran tan fuertes en mí,
que el diputado quedó muy preocupado.

Cuando terminé, él le preguntó al sacerdote qué tenía que decir respecto a mis palabras.
El sacerdote respondió que todo era muy cierto y bueno, y que no tenía nada que objetar,
si yo decía con sinceridad lo que hablaba.
Entonces le dije al sacerdote: "`El Espíritu de Dios es verdadero,
y siempre dice lo que quiere decir, y quiere decir lo que dice;
pero los hombres de mentes corruptas pervierten las
Escrituras al poner sus propias imaginaciones,
conceptos y entendimientos sobre ellas, y así engañan al pueblo.
Pero los hombres santos de Dios dieron las Escrituras
según eran inspirados por el Espíritu Santo;
y no son de interpretación privada,
y son entendidas únicamente cuando se leen en el mismo Espíritu que las dio.`"
Luego regresé a mi alojamiento, que estaba en la casa de un tal capitán Rich.
Cuando este capitán regresó a la casa,
me contó que el lord diputado había quedado tan triste y
melancólico después de que yo había estado con él,
que no había salido a jugar a los bolos, ni a entretenerse con ningún otro pasatiempo.

Así, mi servicio para con Dios fue considerable y Él hizo que prosperara.
De allí me fui a Cork, adonde me había sentido movida a ir primero,
y grandes fueron mis sufrimientos,
porque una prisión fue mi porción en casi todo lugar al que iba.
Allí fui movida a llamar a mis parientes y conocidos con la Palabra del Señor,
y a seguirlos a varias casas del campanario, y muchos fueron mi sufrimientos entre ellos.
Pero dondequiera que el Señor abría mi boca, había algunos que me recibían,
y ellos defendían mi causa contra mis perseguidores.
Mi vida estuvo en peligro varias veces,
pero el Señor me preservó. Una vez fui movida a hablar en el mercado,
donde había un carnicero que juró que partiría mi cabeza en dos,
y tenía un cuchillo de carnicero en alto para hacerlo.
Pero una mujer se le acercó por detrás,
sujetó sus brazos y los sostuvo hasta que un soldado llegó y me rescató.

Aquellos que eran mis antiguos conocidos,
con quienes en otro tiempo había tenido mucha relación, y había pasado mucho tiempo,
y me había alojado en sus casas varias veces,
ahora me temían y no querían acercarse a mí; porque el pavor del Señor estaba conmigo,
y hacía que algunos de ellos temblaran.
Algunos decían que yo era una bruja,
y cuando quería ir a sus casas para reprenderlos por el mal,
se enfurecían tanto que salían huyendo,
y luego llegaban sus siervos y me sacaban a rastras.
A veces, cuando me sentaba, me arrastraban por el suelo,
me arrojaban fuera y cerraban las puertas.
Así llegué a experimentar la verdad de las palabras de Cristo:
"`No hay profeta sin honra sino en su propia tierra.`" Y cuando
sentí que mi conciencia estaba bastante libre por mi servicio allí,
regresé a mi casa en Bristol.

Un tiempo después de esto, fui movida a ir a Irlanda de nuevo,
y en el camino estuve en grandes peligros en el mar,
y vi "`sus maravillas en las profundidades.`"^
footnote:[ Salmos 107:24]
En el barco iban un Amigo y una Amiga además de mí,
y el barco se partió cerca de Dungarvan y comenzó a hundirse en el mar,
no muy lejos de la orilla,
y por un momento se pensó que todo se perdería. El Señor me mandó permanecer
en el barco hasta que todos hubieran salido de él. El capitán del barco
y los pasajeros lograron subir al bote de remos (todos,
excepto un hombre y una mujer que se ahogaron) y llegaron a tierra,
donde se quedaron mirando para ver qué sería de mí;
porque yo todavía estaba en mi camarote, y las olas golpeaban con tal fuerza sobre mí,
que estuve a punto de ahogarme.

Cuando sentí libertad del Señor,
fui y me puse de pie sobre un pedazo de la cubierta que había quedado,
y entonces el capitán del barco y el Amigo me llamaron y me dijeron que, si yo saltaba,
ellos se arriesgarían a meterse en el agua para salvarme.
Así que se metieron en el agua hasta el cuello, y yo salté hacia ellos, y me alcanzaron.
Pero al saltar, quedé enredada entre las cuerdas y fui alejada de ellos otra vez.
Sin embargo, según el Señor lo dispuso,
en ese mismo momento se levantó una ola y golpeó el barco, alejándolo de la orilla;
porque si la ola lo hubiera empujado hacia la costa, nos habría aplastado a los tres.
Pero como el viento empujaba el barco hacia afuera,
me sujetaron de nuevo y me llevaron a tierra.
Así fue como el poder y la misericordia del Señor se manifestaron
maravillosamente en ese momento para mi preservación,
y no puedo sino bendecir Su nombre por ello.

De ahí fui a Dublín, donde hablé en el Alto Tribunal de Justicia ante los jueces,
por lo que fui enviada a prisión. Allí me recostaba sobre paja en el suelo,
y cuando llovía,
la humedad y los excrementos de la cárcel corría por debajo de mi espalda.
Después de un tiempo,
me llevaron a juicio y ordenaron que me declarara culpable o no culpable.
Viendo una trampa en sus palabras,
respondí que no había culpa en la conciencia de nadie
por lo que hacía en obediencia al Señor Dios.
El juez no pudo hablarme directamente,
así que le ordenó a otro hombre que estaba a su lado que me hablara.
Pero como no respondí de la manera que ellos querían, me devolvieron a la prisión,
donde atravesé pruebas muy duras.

En aquel tiempo había en Dublín un hombre rico que
no podía tomar posesión de cierta tierra,
a menos que probara que su hermano había muerto;
y llevó a un hombre a la prisión que decía que él probaría que
el hermano del hombre rico había sido asesinado en cierta posada,
y enterrado bajo un muro.
Este hombre argumentaba que el posadero y su esposa, junto con un sirviente,
una criada y un herrero, eran culpables de ese asesinato.
Así que fui a ver a este hombre, me senté a su lado, y le dije unas pocas palabras.
Le pregunté como había podido esconder ese asesinato por tanto tiempo,
si en efecto era cierto; porque al haberlo ocultado,
se había hecho tan culpable como cualquiera de los otros.
El hombre temblaba y se estremecía tanto mientras yo le hablaba,
que las rodillas le pegaban una contra la otra.
Entonces confesó libremente, que nunca antes había visto a esas personas en su vida,
que nunca había estado en la posada, ni sabía nada del caso,
pero que había sido incitado y persuadido a testificar contra
ellos por el hombre rico que deseaba quedarse con la tierra.

Los otros prisioneros oyeron la confesión que me hizo,
entonces le mandé al alguacil un mensaje para que llamara a su sacerdote,
para que también escuchara la confesión. Cuando el sacerdote llegó,
el hombre le confesó lo mismo que a mí,
y confesó lo mismo privadamente ante el juez Pepes.
Las cinco personas que él había acusado de asesinato estaban en la prisión,
pero sólo la criada estaba conmigo en ese momento, y oyó la confesión del hombre.
Pero el hombre rico--que lo había llevado a prisión--iba a verlo todos los días,
hablaba con él con frecuencia y lo embriagaba.
Y también hizo que el carcelero me encerrara en otro lugar,
para que no me acercara al hombre que había confesado.

Por lo tanto, le escribí de esto al posadero, a su esposa y al sirviente.
También le escribí al juez Pepes, y le dije que veía que el día de su muerte se acercaba,
en el que tendría que dar cuenta de sus actos,
y le advertí que tuviera cuidado de condenar a tantas personas inocentes,
teniendo sólo un testigo en cuya boca había tantas mentiras.
Pero aunque las cinco personas declararon su inocencia,
el juez Pepes los condenó a todos a muerte.

Entonces el sacerdote llegó a hablar con la criada que había sido condenada a la horca,
quien estaba conmigo en la prisión, pero se rehusó a verlo diciendo: "`No,
él no puede hacerme ningún bien.
He acabado con los hombres para siempre.
Pero Dios, Tú sabes que soy inocente de lo que me han imputado.`"
Así que todos fueron ahorcados, y el hombre que los había acusado fue colgado de primero,
por temor a que confesara la verdad después de ver a los otros morir.
En verdad, fue un día muy doloroso, y soporté y sufrí mucho ese día.

En ese tiempo, unos amigos míos--a saber; Sir William King,
Colonel Fare y la señora Browne--al enterarse de que yo estaba en prisión,
vinieron a verme.
Dijeron que irían de inmediato a ver y hablar con el juez Pepes para obtener mi libertad.
Pero cuando llegaron donde él, les dijo que me tenía miedo y temía por su vida.
Ellos rieron y le dijeron que me conocían desde niña,
y que no había ningún mal en mí. Todos fueron muy insistentes en procurar mi libertad,
y al final la obtuvieron.
Una vez libre, fui movida a ir a la casa del campanario donde se hallaba este juez,
y el Señor estaba conmigo.
Le entregué todo lo que el Señor había puesto sobre mí; y luego se fue a su casa,
se acostó y murió esa noche.
Unos de los prisioneros había leído la carta que yo le había enviado,
y cuando supieron que el juez había muerto,
dijeron que yo había sido una verdadera profetiza para él.

Así, como instrumento en la mano del Señor para hacer Su obra,
fue fiel y obediente a Su poder,
y Él me hizo crecer y prosperar por medio de mis grandes sufrimientos,
de modo que--bendito sea Su nombre para siempre--tuve
gran experiencia de Su amor y de Su poder.
Elizabeth Gardiner,
Rebecca Rich y la esposa de Samuel Claridge saben que todo esto es verdad.

De allí fui a Limerick, donde tuve algún servicio y fui nuevamente encarcelada.
Pero después de un tiempo fui liberada, y entonces tomé un barco rumbo a Inglaterra.
Una vez más, nos alcanzó una gran tormenta en el mar, y el Señor me movió a orar,
y en poco tiempo la tormenta paró y fuimos preservados.
Al acercarnos a Mineyard,
nos topamos con un barco pirata que tenía una gran cantidad de hombres a bordo,
y comencé a considerar si había algún servicio que pudiera realizar entre esa gente ruda,
pero hallé poco hacia ellos.
Subieron a bordo de nuestro barco y me quitaron lo que tenía,
incluso uno de los abrigos que llevaba encima,
pero no se les permitió hacerme mayor daño. Se llevaron con ellos al capitán del barco,
hasta que él les pagara una suma de dinero por el barco y las mercancías;
pero al fin llegamos a Inglaterra.
En todos mis viajes siempre anduve por mi propia cuenta y nunca fui carga para nadie,
sino que pagaba por todas mis necesidades.

Mucho más podría relatar acerca de los sufrimientos por los que he pasado,
pero me abstengo, no queriendo ser tediosa.
Y he escrito estas cosas con el único propósito de que los Amigos sean alentados
y perseveren en la fe y en la obra del Señor. Porque muchas han sido las pruebas,
tribulaciones y aflicciones que he atravesado,
pero el Señor me ha liberado de todas ellas.

¡A Él sea la gloria, y bendito sea Su nombre por los siglos de los siglos!

[.signed-section-signature]
Bárbara Blaugdone
